"""
FastForge Generic Repository
================================
generic repository with built-in:
  - Pagination
  - Search across string fields
  - Sorting
  - Soft-delete filtering (automatic)
  - Multi-tenant filtering (automatic)

The CRUD generator creates entity-specific repos that extend this.
You rarely need to use this directly.

Usage:
    # Auto-generated by `fastforge crud`
    class ProductRepository(GenericRepository[Product]):
        searchable_fields = ["name", "description", "sku"]
"""
from __future__ import annotations
from typing import TypeVar, Generic, Type, Optional, Any
from dataclasses import dataclass
from sqlalchemy.orm import Session
from sqlalchemy import or_, func, String, inspect

from .entities import Base

T = TypeVar("T", bound=Base)


@dataclass
class PagedResult:
    """Paginated query result — matches FastForge's IPagedResult."""
    items: list
    total: int
    page: int
    page_size: int

    @property
    def total_pages(self) -> int:
        if self.page_size <= 0:
            return 0
        return (self.total + self.page_size - 1) // self.page_size


class GenericRepository(Generic[T]):
    """
    Generic repository with CRUD + pagination + search + sort.

    Automatically handles:
      - Soft delete filtering (if entity has is_deleted)
      - Multi-tenant filtering (if entity has tenant_id)
      - Audit field population (created_by, updated_by)
    """

    # Override in subclass to enable search
    searchable_fields: list[str] = []

    # Override to add default ordering
    default_sort_field: str = "id"
    default_sort_order: str = "asc"

    def __init__(self, db: Session, model_class: Type[T], current_user_id: Optional[str] = None, current_tenant_id: Optional[str] = None):
        self.db = db
        self.model_class = model_class
        self.current_user_id = current_user_id
        self.current_tenant_id = current_tenant_id

    # ─── Base Query (with automatic filters) ─────────────────────────────

    def _base_query(self):
        """Build base query with soft-delete and tenant filters applied."""
        query = self.db.query(self.model_class)

        # Auto soft-delete filter
        if hasattr(self.model_class, "is_deleted"):
            query = query.filter(self.model_class.is_deleted == False)

        # Auto multi-tenant filter
        if hasattr(self.model_class, "tenant_id") and self.current_tenant_id:
            query = query.filter(self.model_class.tenant_id == self.current_tenant_id)

        return query

    # ─── Read Operations ─────────────────────────────────────────────────

    def get_by_id(self, id) -> Optional[T]:
        """Get a single entity by ID. Returns None if not found or soft-deleted."""
        return self._base_query().filter(self.model_class.id == id).first()

    def get_list(
        self,
        page: int = 1,
        page_size: int = 20,
        search: Optional[str] = None,
        sort_by: Optional[str] = None,
        sort_order: Optional[str] = None,
        filters: Optional[dict[str, Any]] = None,
    ) -> PagedResult:
        """
        Get paginated list with search, sort, and filters.
        This is the workhorse method — equivalent to FastForge's GetListAsync.
        """
        query = self._base_query()

        # Apply search across searchable fields
        if search and self.searchable_fields:
            conditions = []
            for field_name in self.searchable_fields:
                col = getattr(self.model_class, field_name, None)
                if col is not None:
                    conditions.append(col.ilike(f"%{search}%"))
            if conditions:
                query = query.filter(or_(*conditions))

        # Apply exact-match filters
        if filters:
            for field_name, value in filters.items():
                if value is None:
                    continue
                col = getattr(self.model_class, field_name, None)
                if col is not None:
                    query = query.filter(col == value)

        # Count before pagination
        total = query.count()

        # Sorting
        sort_field = sort_by or self.default_sort_field
        order = sort_order or self.default_sort_order
        sort_col = getattr(self.model_class, sort_field, None)
        if sort_col is None:
            sort_col = getattr(self.model_class, "id")
        if order == "desc":
            query = query.order_by(sort_col.desc())
        else:
            query = query.order_by(sort_col.asc())

        # Pagination
        offset = (page - 1) * page_size
        items = query.offset(offset).limit(page_size).all()

        return PagedResult(items=items, total=total, page=page, page_size=page_size)

    def get_all(self) -> list[T]:
        """Get all entities (no pagination). Use sparingly."""
        return self._base_query().all()

    def count(self, filters: Optional[dict[str, Any]] = None) -> int:
        """Count entities matching optional filters."""
        query = self._base_query()
        if filters:
            for field_name, value in filters.items():
                if value is None:
                    continue
                col = getattr(self.model_class, field_name, None)
                if col is not None:
                    query = query.filter(col == value)
        return query.count()

    def exists(self, id) -> bool:
        """Check if entity exists."""
        return self.get_by_id(id) is not None

    # ─── Write Operations ────────────────────────────────────────────────

    def create(self, entity: T) -> T:
        """Insert a new entity. Auto-sets audit fields."""
        if hasattr(entity, "created_by") and self.current_user_id:
            entity.created_by = self.current_user_id
            entity.updated_by = self.current_user_id
        if hasattr(entity, "tenant_id") and self.current_tenant_id:
            entity.tenant_id = self.current_tenant_id

        self.db.add(entity)
        self.db.commit()
        self.db.refresh(entity)
        return entity

    def update(self, entity: T) -> T:
        """Update an entity. Auto-sets updated_by/updated_at."""
        if hasattr(entity, "updated_by") and self.current_user_id:
            entity.updated_by = self.current_user_id

        self.db.commit()
        self.db.refresh(entity)
        return entity

    def delete(self, id) -> bool:
        """
        Delete an entity. Uses soft-delete if available, hard-delete otherwise.
        
        """
        entity = self.get_by_id(id)
        if not entity:
            return False

        if hasattr(entity, "is_deleted"):
            # Soft delete
            entity.is_deleted = True
            if hasattr(entity, "deleted_by") and self.current_user_id:
                entity.deleted_by = self.current_user_id
            from datetime import datetime, timezone
            if hasattr(entity, "deleted_at"):
                entity.deleted_at = datetime.now(timezone.utc)
            self.db.commit()
        else:
            # Hard delete
            self.db.delete(entity)
            self.db.commit()
        return True

    def bulk_delete(self, ids: list) -> int:
        """Delete multiple entities by ID."""
        count = 0
        for id in ids:
            if self.delete(id):
                count += 1
        return count

    # ─── Helpers ─────────────────────────────────────────────────────────

    def create_from_dict(self, data: dict) -> T:
        """Create entity from a dictionary (typically from Pydantic .model_dump())."""
        entity = self.model_class(**data)
        return self.create(entity)

    def update_from_dict(self, id, data: dict, exclude_unset: bool = True) -> Optional[T]:
        """Update entity from a dictionary."""
        entity = self.get_by_id(id)
        if not entity:
            return None
        for field, value in data.items():
            if exclude_unset and value is None:
                continue
            if hasattr(entity, field):
                setattr(entity, field, value)
        return self.update(entity)
